config/routes.rb
ThatDriver::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get '/get_token', to: 'api#get_token'
      post '/register', to: 'api#register'

      get '/get_taxi', to: 'taxis#get_taxi'
      post '/rate_taxi', to: 'taxis#rate_taxi'
      get '/ratings_summary', to: 'taxis#ratings_summary'
      get '/get_ratings', to: 'taxis#get_ratings'

      get '/myreports', to: 'items#get_my_report'
      get '/my_lost_and_found', to:'items#get_lost_and_found'
      get '/allreports', to: 'items#get_all_report'
      post '/report_lost', to: 'items#report_lost'
      post '/report_found', to: 'items#report_found'
      post '/resolve_item', to: 'items#resolve_item'
      post '/update_item', to: 'items#update_item'
      post '/delete_item', to: 'items#delete_item'

      resources :reports, only:[:index,:show,:create,:update,:destroy]
    end
  end

  resources :found_items

  resources :items
  resources :rates

  resources :taxis

  root :to => 'home#index'

  get "home/index"

  devise_for :users
  resources :users

  

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # load_and_authorize_resource #cancan method


  def index
    @taxis = Taxi.all.limit(20)
    @users = User.all.limit(20)
    @items = Item.all.limit(20)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Home#index

- if is_admin
  %h1 YOU ARE AN ADMIN
- else
  %h1 YOU ARE A USER, YOU SHOULDN't BE HERE!

- if current_user.role == 'admin'
  %table.table
    %tr
      %th Returned
      %th Location
      %th When
      %th
      %th
      %th

    - @items.each do |item|
      %tr
        %td= item.returned
        %td= item.location
        %td= item.when
        %td= link_to 'Show', item, class:"btn btn-success"
        %td= link_to 'Edit', edit_item_path(item), class:"btn btn-primary"
        %td= link_to 'Destroy', item, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-danger"
  %br
  %table.table
    %tr
      %th Username
      %th First Name
      %th Last Name
      %th Email
      %th Phone
      %th

    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td= user.phone
        %td= link_to 'Show', user, class:"btn btn-success"
        %td= link_to 'Edit', edit_user_path(user), class:"btn btn-primary"
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-danger"
  %br
  %table.table
    %tr
      %th Plate No.
      %th Province
      %th Owner
      %th
      %th
      %th

    - @taxis.each do |taxi|
      %tr
        %td= taxi.plate_no
        %td= taxi.province
        %td= taxi.owner
        %td= link_to 'Show', taxi, class:"btn btn-success"
        %td= link_to 'Edit', edit_taxi_path(taxi), class:"btn btn-primary"
        %td= link_to 'Destroy', taxi, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-danger"