config/routes.rb
ThatDriver::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get '/get_token', to: 'api#get_token'
      post '/register', to: 'api#register'

      get '/get_taxi', to: 'taxis#get_taxi'
      post '/rate_taxi', to: 'taxis#rate_taxi'
      get '/ratings_summary', to: 'taxis#ratings_summary'
      get '/get_ratings', to: 'taxis#get_ratings'

      get '/myreports', to: 'items#get_my_report'
      get '/my_lost_and_found', to:'items#get_lost_and_found'
      get '/allreports', to: 'items#get_all_report'
      post '/report_lost', to: 'items#report_lost'
      post '/report_found', to: 'items#report_found'
      post '/resolve_item', to: 'items#resolve_item'
      post '/update_item', to: 'items#update_item'
      post '/delete_item', to: 'items#delete_item'

      resources :reports, only:[:index,:show,:create,:update,:destroy]
    end
  end

  resources :found_items

  resources :items
  resources :rates

  resources :taxis

  root :to => 'home#index'

  get "home/index"

  devise_for :users
  resources :users

  

  

end

app/helpers/found_items_helper.rb
module FoundItemsHelper
end

app/views/found_items/_form.html.haml
= form_for @found_item do |f|
  - if @found_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@found_item.errors.count, "error")} prohibited this found_item from being saved:"
      %ul
        - @found_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :returned
    = f.check_box :returned
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :when
    = f.datetime_select :when
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :belongs_to
    = f.text_field :belongs_to
  .actions
    = f.submit 'Save'

app/views/found_items/edit.html.haml
%h1 Editing found_item

= render 'form'

= link_to 'Show', @found_item
\|
= link_to 'Back', found_items_path

app/views/found_items/index.html.haml
%h1 Listing found_items

%table
  %tr
    %th Returned
    %th Location
    %th When
    %th Description
    %th Belongs to
    %th
    %th
    %th

  - @found_items.each do |found_item|
    %tr
      %td= found_item.returned
      %td= found_item.location
      %td= found_item.when
      %td= found_item.description
      %td= found_item.belongs_to
      %td= link_to 'Show', found_item
      %td= link_to 'Edit', edit_found_item_path(found_item)
      %td= link_to 'Destroy', found_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Found item', new_found_item_path

app/views/found_items/new.html.haml
%h1 New found_item

= render 'form'

= link_to 'Back', found_items_path

app/views/found_items/show.html.haml
%p#notice= notice

%p
  %b Returned:
  = @found_item.returned
%p
  %b Location:
  = @found_item.location
%p
  %b When:
  = @found_item.when
%p
  %b Description:
  = @found_item.description
%p
  %b Belongs to:
  = @found_item.belongs_to

= link_to 'Edit', edit_found_item_path(@found_item)
\|
= link_to 'Back', found_items_path