config/routes.rb
ThatDriver::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get '/get_token', to: 'api#get_token'
      post '/register', to: 'api#register'

      get '/get_taxi', to: 'taxis#get_taxi'
      post '/rate_taxi', to: 'taxis#rate_taxi'
      get '/ratings_summary', to: 'taxis#ratings_summary'
      get '/get_ratings', to: 'taxis#get_ratings'

      get '/myreports', to: 'items#get_my_report'
      get '/my_lost_and_found', to:'items#get_lost_and_found'
      get '/allreports', to: 'items#get_all_report'
      post '/report_lost', to: 'items#report_lost'
      post '/report_found', to: 'items#report_found'
      post '/resolve_item', to: 'items#resolve_item'
      post '/update_item', to: 'items#update_item'
      post '/delete_item', to: 'items#delete_item'

      resources :reports, only:[:index,:show,:create,:update,:destroy]
    end
  end

  resources :found_items

  resources :items
  resources :rates

  resources :taxis

  root :to => 'home#index'

  get "home/index"

  devise_for :users
  resources :users

  

  

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :user
  belongs_to :taxi
  validates :user_id, :taxi_id, :rating, presence: true
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rate }
      else
        format.html { render action: 'new' }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:comment, :rating)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.haml
= form_for @rate do |f|
  - if @rate.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rate.errors.count, "error")} prohibited this rate from being saved:"
      %ul
        - @rate.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :comment
    = f.text_area :comment
  .field
    = f.label :rating
    = f.number_field :rating
  .actions
    = f.submit 'Save'

app/views/rates/edit.html.haml
%h1 Editing rate

= render 'form'

= link_to 'Show', @rate
\|
= link_to 'Back', rates_path

app/views/rates/index.html.haml
%h1 Listing rates

%table
  %tr
    %th Comment
    %th Rating
    %th
    %th
    %th

  - @rates.each do |rate|
    %tr
      %td= rate.comment
      %td= rate.rating
      %td= link_to 'Show', rate
      %td= link_to 'Edit', edit_rate_path(rate)
      %td= link_to 'Destroy', rate, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Rate', new_rate_path

app/views/rates/new.html.haml
%h1 New rate

= render 'form'

= link_to 'Back', rates_path

app/views/rates/show.html.haml
%p#notice= notice

%p
  %b Comment:
  = @rate.comment
%p
  %b Rating:
  = @rate.rating

= link_to 'Edit', edit_rate_path(@rate)
\|
= link_to 'Back', rates_path